/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsNotFoundRouteImport } from './routes/docs/not-found'
import { Route as DocsSearchDotjsonRouteImport } from './routes/docs/search[.]json'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'

const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsNotFoundRoute = DocsNotFoundRouteImport.update({
  id: '/docs/not-found',
  path: '/docs/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSearchDotjsonRoute = DocsSearchDotjsonRouteImport.update({
  id: '/docs/search.json',
  path: '/docs/search.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/not-found': typeof DocsNotFoundRoute
  '/docs/search.json': typeof DocsSearchDotjsonRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/not-found': typeof DocsNotFoundRoute
  '/docs/search.json': typeof DocsSearchDotjsonRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/not-found': typeof DocsNotFoundRoute
  '/docs/search.json': typeof DocsSearchDotjsonRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/docs/$'
    | '/docs/not-found'
    | '/docs/search.json'
    | '/docs/{$}.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/docs/$'
    | '/docs/not-found'
    | '/docs/search.json'
    | '/docs/{$}.md'
  id:
    | '__root__'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/docs/$'
    | '/docs/not-found'
    | '/docs/search.json'
    | '/docs/{$}.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsNotFoundRoute: typeof DocsNotFoundRoute
  DocsSearchDotjsonRoute: typeof DocsSearchDotjsonRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/not-found': {
      id: '/docs/not-found'
      path: '/docs/not-found'
      fullPath: '/docs/not-found'
      preLoaderRoute: typeof DocsNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/search.json': {
      id: '/docs/search.json'
      path: '/docs/search.json'
      fullPath: '/docs/search.json'
      preLoaderRoute: typeof DocsSearchDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsNotFoundRoute: DocsNotFoundRoute,
  DocsSearchDotjsonRoute: DocsSearchDotjsonRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
