// Generated by apps/explore/scripts/tokens.ts from @monad-crypto/token-list 2.49.0, @web3icons/common 0.11.53
// and @web3icons/core 4.0.58. Do not edit; rerun the script. Logos: public/tokens/<chainId>/<address>.png.

/** Tokens with a vendored logo, keyed `<chainId>:<lowercase address>`. Being on a list is not Hireling's endorsement. */
export const TOKEN_LOGOS: Readonly<Record<string, { symbol: string; name: string; decimals: number; source: 'monad-list' | 'web3icons' }>> = {
  "10143:0x0000000000000000000000000000000000000000": {
    "symbol": "MON",
    "name": "Monad",
    "decimals": 18,
    "source": "monad-list"
  },
  "10143:0x45477f4709771331db81944a5e20ef95bc7ba2d7": {
    "symbol": "WETH",
    "name": "Wrapped Ether",
    "decimals": 18,
    "source": "monad-list"
  },
  "10143:0x534b2f3a21130d7a60830c2df862319e593943a3": {
    "symbol": "USDC",
    "name": "USDC",
    "decimals": 6,
    "source": "monad-list"
  },
  "10143:0xfb8bf4c1cc7a94c73d209a149ea2abea852bc541": {
    "symbol": "WMON",
    "name": "Wrapped MON",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x0000000000000000000000000000000000000000": {
    "symbol": "MON",
    "name": "Monad",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x00000000efe302beaa2b3e6e1b18d08d69a9012a": {
    "symbol": "AUSD",
    "name": "AUSD",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x0143c3ef3a76ed825fd5201953f65b52acefd799": {
    "symbol": "gAUSD",
    "name": "K3 x Galaxy Lending",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x01bff41798a0bcf287b996046ca68b395dbc1071": {
    "symbol": "XAUt0",
    "name": "XAUt0",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x04f8c38ae80bcf690b947f60f62bda18145c3d67": {
    "symbol": "MVT",
    "name": "Monad Vault",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x0555e30da8f98308edb960aa94c0db47230d2b9c": {
    "symbol": "WBTC",
    "name": "Wrapped BTC",
    "decimals": 8,
    "source": "monad-list"
  },
  "143:0x09d4214c03d01f49544c0448dbe3a27f768f2b34": {
    "symbol": "rUSD",
    "name": "Reservoir Stablecoin",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x0bb150dfa86ea5d7742f07fefcd8e8eda81d64ef": {
    "symbol": "USDat",
    "name": "Saturn USD",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x0c65a0bc65a5d819235b71f554d210d3f80e0852": {
    "symbol": "aprMON",
    "name": "aPriori Monad LST",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x0cb6d03b0ac88a463f67b7ad99f9f3ec4678092e": {
    "symbol": "SOFID",
    "name": "SoFiUSD",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x0d9d741fe423cd5419e4bcb6cb2ffa87afa93ba4": {
    "symbol": "avUSD",
    "name": "avUSD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x1001ff13bf368aa4fa85f21043648079f00e1001": {
    "symbol": "LV",
    "name": "LeverUp",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x103222f020e98bba0ad9809a011fdf8e6f067496": {
    "symbol": "earnAUSD",
    "name": "earnAUSD",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x10aeaf63194db8d453d4d85a06e5efe1dd0b5417": {
    "symbol": "wstETH",
    "name": "Wrapped liquid staked Ether 2.0",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x111111d2bf19e43c34263401e0cad979ed1cdb61": {
    "symbol": "USD1",
    "name": "World Liberty Financial USD",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x1111b3ded9f1fe1801ad4ebef8e2788183a24111": {
    "symbol": "EURW",
    "name": "Newrails Euro",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x137643f7b2c189173867b3391f6629cab46f0f1a": {
    "symbol": "sfrxUSD",
    "name": "Staked Frax USD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x17b8f7373ecd556192abfc85be314e5d4fb6b3fa": {
    "symbol": "srUSDat",
    "name": "srUSDat",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x1808d4aa4d4a7cf66bb6515bf126edefa2b018c1": {
    "symbol": "USD*",
    "name": "USD Star",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x18bc5bcc660cf2b9ce3cd51a404afe1a0cbd3c22": {
    "symbol": "IDRX",
    "name": "IDRX",
    "decimals": 2,
    "source": "monad-list"
  },
  "143:0x1b68626dca36c7fe922fd2d55e4f631d962de19c": {
    "symbol": "shMON",
    "name": "ShMonad",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x1c22531aa9747d76fff8f0a43b37954ca67d28e0": {
    "symbol": "suETH",
    "name": "Sumerian ETH",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x1c8ee940b654bfced403f2a44c1603d5be0f50fa": {
    "symbol": "mEDGE",
    "name": "Midas mEDGE",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x1d4795a4670033f47f572b910553be0295077b51": {
    "symbol": "mcMON",
    "name": "mcMON",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x211cc4dd073734da055fbf44a2b4667d5e5fe5d2": {
    "symbol": "sUSDe",
    "name": "Staked USDe",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x22f6a6752800eab67b84748fefc3cc658384af72": {
    "symbol": "JPYm",
    "name": "Mento Japanese Yen",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x2416092f143378750bb29b79ed961ab195cceea5": {
    "symbol": "ezETH",
    "name": "Renzo Restaked ETH",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x288f9d76019469bfeb56bb77d86afa2bf563b75b": {
    "symbol": "frxETH",
    "name": "Frax Ether",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x29acc7c504665a5ea95344796f784095f0cfcc58": {
    "symbol": "WFRAX",
    "name": "Wrapped Frax",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x2abc42250154752273a4560e875c858623f83ecc": {
    "symbol": "aguaUSDCgc",
    "name": "Agua Global Carry Vault",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x2fabf1c784b8583d63c00c5c9c0377d8cf1a3245": {
    "symbol": "ACRDX",
    "name": "Anemoy Tokenized Apollo Diversified Credit Fund Token",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x336d414754967c6682b5a665c7daf6f1409e63e8": {
    "symbol": "muBOND",
    "name": "mu Bond",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x37d6382b6889ccef8d6871a8b60e667115eddbcf": {
    "symbol": "pufETH",
    "name": "pufETH",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x39bb4e0a204412bb98e821d25e7d955e69d40fd1": {
    "symbol": "GBPm",
    "name": "Mento British Pound",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x3a2c4aaae6776dc1c31316de559598f2f952e2cb": {
    "symbol": "YZM",
    "name": "Yuzu Money Vault",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x3b4cf37a3335f21c945a40088404c715525fcb29": {
    "symbol": "sfrxETH",
    "name": "Staked Frax Ether",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x3bd359c1119da7da1d913d1c4d2b7c461115433a": {
    "symbol": "WMON",
    "name": "Wrapped MON",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x3fea1cb36d2c5523c062d0e060eac253608b4daf": {
    "symbol": "FUSDLP",
    "name": "FinChain Dollar LP",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x437cc33344a0b27a429f795ff6b469c72698b291": {
    "symbol": "wM",
    "name": "WrappedM by M0",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x46080f31351a6568f44575e3effde7f0c86867f9": {
    "symbol": "GILTS",
    "name": "Etherfuse GILTS",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x4809010926aec940b550d34a46a52739f996d75d": {
    "symbol": "wsrUSD",
    "name": "Wrapped Savings rUSD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x484be0540ad49f351eaa04eeb35df0f937d4e73f": {
    "symbol": "syzUSD",
    "name": "Staked Yuzu USD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x4917a5ec9fcb5e10f47cbb197abe6ab63be81fe8": {
    "symbol": "AZND",
    "name": "Asian Dollar",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x4d502d735b4c574b487ed641ae87ceae884731c7": {
    "symbol": "EURm",
    "name": "Mento Euro",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x58538e6a46e07434d7e7375bc268d3cb839c0133": {
    "symbol": "ENA",
    "name": "ENA",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x58ba69b289de313e66a13b7d1f822fc98b970554": {
    "symbol": "naccUSDC",
    "name": "sUSN Delta Neutral Yield Vault",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x58e3ee6accd124642ddb5d3f91928816be8d8ed3": {
    "symbol": "frxUSD",
    "name": "Frax USD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34": {
    "symbol": "USDe",
    "name": "USDe",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x5e49e1f85813f2b65858860a3fa231b4186f2e0e": {
    "symbol": "PENDLE",
    "name": "Pendle",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x5ec32e3f2cc925296dc37edf3b2388868d5525c5": {
    "symbol": "jrUSDat",
    "name": "jrUSDat",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x5f8a1c74c112865bd05dbe4752c7608332719062": {
    "symbol": "deJAAA",
    "name": "JAAA deRWA",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x61b29efef2e6f866ba4aaefdb87d2837c6a22b9c": {
    "symbol": "sLVMON",
    "name": "Staked LVMON",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x650b616b46ff94000eb115926ab8393b90788d76": {
    "symbol": "rwaUSDi",
    "name": "rwaUSDi",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x683fb58ee77172626d5b49087ddac71ef7825d20": {
    "symbol": "strUSD",
    "name": "Staked trUSD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x6cf55183ea297ba200cf88419bba156eba2ed206": {
    "symbol": "mROX",
    "name": "Midas Rockaway Market Neutral",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x754704bc059f8c67012fed69bc8a327a5aafb603": {
    "symbol": "USDC",
    "name": "USDC",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x76f257b1dda5cc71bee4ef637fbdde4c801310a9": {
    "symbol": "LINK",
    "name": "ChainLink Token",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x770a579ea200784723b31b8668b0773ba80393c9": {
    "symbol": "trUSD",
    "name": "trUSD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x7a9990ffe3057edc18558ca4c8804430fe917456": {
    "symbol": "TESOURO",
    "name": "Etherfuse TESOURO",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x7cd231120a60f500887444a9baf5e1bd753a5e59": {
    "symbol": "aHYPER",
    "name": "Hyperithm Delta Neutral Vault",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x7cee47e7b7cd04cf984e8dd86c42595b5771a9b2": {
    "symbol": "USTRY",
    "name": "Etherfuse USTRY",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x834df4c1d8f51be24322e39e4766697be015512f": {
    "symbol": "CETES",
    "name": "Etherfuse CETES",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x8498312a6b3cbd158bf0c93abdcf29e6e4f55081": {
    "symbol": "gMON",
    "name": "gMON",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x866a2bf4e572cbcf37d5071a7a58503bfb36be1b": {
    "symbol": "M",
    "name": "M by M0",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x8bf591eae535f93a242d5a954d3cde648b48a5a8": {
    "symbol": "suUSD",
    "name": "Sumerian USD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x8d3f9f9eb2f5e8b48efbb4074440d1e2a34bc365": {
    "symbol": "vUSD",
    "name": "RWA Backed Lending by Valos",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0x8de0f3295b9e42b29e7617bada7c603277420451": {
    "symbol": "deJTRSY",
    "name": "JTRSY deRWA",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x8fa1365f6e39b7404737721a356b1d4a7b11ca7d": {
    "symbol": "earnMON",
    "name": "earnMON",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x91b81bfbe3a747230f0529aa28d8b2bc898e6d56": {
    "symbol": "LVMON",
    "name": "LeverUp MON",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x91d93dbd823221ea9e54fb3e447bd917ce41f2e8": {
    "symbol": "AA_FalconXUSDC",
    "name": "Pareto AA Tranche - FalconXUSDC",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x9648db94f1e6b19e7d755585542981f97dc806c6": {
    "symbol": "savUSD",
    "name": "Staked avUSD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x9abb5aaaa4c63abee1b6617843fd818c99c52c69": {
    "symbol": "rwaUSD",
    "name": "Real World Asset USD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x9c82eb49b51f7dc61e22ff347931ca32adc6cd90": {
    "symbol": "loAZND",
    "name": "Locked AZND",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x9cd57d3685e6868cacaa8bdcaaf52cbdebf4fa25": {
    "symbol": "sUSDat",
    "name": "Staked Saturn USD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x9dcb0d17edde04d27f387c89fecb78654c373858": {
    "symbol": "yzUSD",
    "name": "Yuzu USD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x9e2679eabff131b8b1b48ff7566140794e0eedc4": {
    "symbol": "deCRDX",
    "name": "ACRDX deRWA",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0x9f6714c302ffe3c3bafaf2ccb44201ff64f6371c": {
    "symbol": "FUSD",
    "name": "FinChain Dollar",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xa3227c5969757783154c60bf0bc1944180ed81b9": {
    "symbol": "sMON",
    "name": "Kintsu Staked Monad",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xa3d68b74bf0528fdd07263c60d6488749044914b": {
    "symbol": "weETH",
    "name": "Wrapped eETH",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xab6e5a0c3799d020c790d34f7b2c02639e238af7": {
    "symbol": "syrupUSDC",
    "name": "Syrup USDC",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xaca92e438df0b2401ff60da7e4337b687a2435da": {
    "symbol": "mUSD",
    "name": "MetaMask USD",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xad48f183e586e92a591a610397ebf534609df797": {
    "symbol": "JAAA",
    "name": "Janus Henderson AAA CLO Fund",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xad663ac84052b52be4ed1b27ba416505e84a00bf": {
    "symbol": "hyAUSD",
    "name": "High Yield AUSD Vault",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xad96c3dffcd6374294e2573a7fbba96097cc8d7c": {
    "symbol": "DUST",
    "name": "Pixie Dust",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xae4efbc7736f963982aacb17efa37fcbab924cb3": {
    "symbol": "SolvBTC",
    "name": "Solv BTC",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xb0f70c0bd6fd87dbeb7c10dc692a2a6106817072": {
    "symbol": "BTC.b",
    "name": "Bitcoin",
    "decimals": 8,
    "source": "monad-list"
  },
  "143:0xb37476cb1f6111cc682b107b747b8652f90b0984": {
    "symbol": "yzPP",
    "name": "Yuzu Protection Pool",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xbc69212b8e4d445b2307c9d32dd68e2a4df00115": {
    "symbol": "USDm",
    "name": "Mento Dollar",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xc18e6f730896971a79d748e8dea61067a9bc6040": {
    "symbol": "JTRSY",
    "name": "Janus Henderson Treasury Fund",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xc50f2e735edd9dcd8ccd41ecfe9894e679e3195f": {
    "symbol": "rETH",
    "name": "Rocket Pool ETH",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xc6221856e45ed806f8325a084bed3d69d32c526d": {
    "symbol": "EUROB",
    "name": "Etherfuse EUROB",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xc6de1dc0b59682be906e5bca14e385e74ee88168": {
    "symbol": "aHyperBTC",
    "name": "Hyperithm Delta Neutral cbBTC Vault",
    "decimals": 8,
    "source": "monad-list"
  },
  "143:0xc99f5c922dae05b6e2ff83463ce705ef7c91f077": {
    "symbol": "xSolvBTC",
    "name": "xSolvBTC",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xc9ea90692757831d98ac629f2a0140e02b80a7da": {
    "symbol": "yzPrime",
    "name": "Yuzu Prime",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xce6170ea245dc8d1f275a710a062b70f125f0110": {
    "symbol": "FXRP",
    "name": "FXRP",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xd18b7ec58cdf4876f6afebd3ed1730e4ce10414b": {
    "symbol": "cbBTC",
    "name": "Coinbase Wrapped BTC",
    "decimals": 8,
    "source": "monad-list"
  },
  "143:0xd25f563e12ff616262f8c947fec108db934f8059": {
    "symbol": "reUSD",
    "name": "Re Protocol reUSD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xd33f18d8d48cbbb2f8b47063de97f94de0d49b99": {
    "symbol": "NXPC",
    "name": "NXPC",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xd691b0afed67f96cec28ab6308cbe5b2c103b7e9": {
    "symbol": "eBTC",
    "name": "eBTC",
    "decimals": 10,
    "source": "monad-list"
  },
  "143:0xd74fb32112b1ef5b4c428fead8da8d85a0019009": {
    "symbol": "xUSDC",
    "name": "xUSDC",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xd793c04b87386a6bb84ee61d98e0065fde7fda5e": {
    "symbol": "sAUSD",
    "name": "sAUSD",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xd7acb868f97f8286d5d3a0fd5ef112a8a72ecd90": {
    "symbol": "enzoBTC",
    "name": "Lorenzo Wrapped Bitcoin",
    "decimals": 8,
    "source": "monad-list"
  },
  "143:0xd90f6bfed23ffde40106fc4498dd2e9edb95e4e7": {
    "symbol": "mHYPER",
    "name": "Midas Hyperithm",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xdef72af3fc69e1dd5a094f7dda08ba203cd0438b": {
    "symbol": "EUL",
    "name": "Euler",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xe7cd86e13ac4309349f30b3435a9d337750fc82d": {
    "symbol": "USDT0",
    "name": "USDT0",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xe85411c030fb32a9d8b14bbbc6cb19417391f711": {
    "symbol": "suBTC",
    "name": "Sumerian BTC",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xe9c082921dc3564e10196c5cc15db1250ac7d5c6": {
    "symbol": "KTB",
    "name": "Etherfuse KTB",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xea17e5a9efebf1477db45082d67010e2245217f1": {
    "symbol": "SOL",
    "name": "Wrapped SOL",
    "decimals": 9,
    "source": "monad-list"
  },
  "143:0xea7e0955d410c5ba9dac457539ef0fa53a1399ed": {
    "symbol": "earnAUSDloop",
    "name": "earnAUSD Loop",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xecac9c5f704e954931349da37f60e39f515c11c1": {
    "symbol": "LBTC",
    "name": "Lombard Staked Bitcoin",
    "decimals": 8,
    "source": "monad-list"
  },
  "143:0xed5aa9b6eb62298492c7246fe724ee088a760155": {
    "symbol": "afi-rwaUSDi",
    "name": "Artificial Financial Intelligence rwaUSDi",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xee8c0e9f1bffb4eb878d8f15f368a02a35481242": {
    "symbol": "WETH",
    "name": "Wrapped Ether",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xf59d81cd43f620e722e07f9cb3f6e41b031017a3": {
    "symbol": "Cake",
    "name": "PancakeSwap Token",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xf64e91ffef7ef43aa314f0bc2ac39f770797990c": {
    "symbol": "CHFm",
    "name": "Mento Swiss Franc",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xf7cf282ec810fded974f99c0163e792f432892bc": {
    "symbol": "mHyperBTC",
    "name": "Midas Hyperithm BTC",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xfc421ad3c883bf9e7c4f42de845c4e4405799e73": {
    "symbol": "GHO",
    "name": "Gho Token",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xfd44b35139ae53fff7d8f2a9869c503d987f00d1": {
    "symbol": "LVUSD",
    "name": "LeverUp USD",
    "decimals": 18,
    "source": "monad-list"
  },
  "143:0xfdd22ce6d1f66bc0ec89b20bf16ccb6670f55a5a": {
    "symbol": "thBILL",
    "name": "thBILL",
    "decimals": 6,
    "source": "monad-list"
  },
  "143:0xff7f8f301f7a706e3cfd3d2275f5dc0b9ee8009b": {
    "symbol": "FOLKS",
    "name": "Folks Finance",
    "decimals": 6,
    "source": "monad-list"
  }
}

/** web3icons' Monad mark, for explorer links. */
export const MONAD_BADGE = '/tokens/monad.png'
