export const prodSecretSources = {
  MONAD_RPC_URL: 'MONAD_RPC_URL',
  RELAY_PRIVATE_KEY: 'RELAY_PRIVATE_KEY',
  ATTESTER_PRIVATE_KEY: 'ATTESTER_PRIVATE_KEY',
  AI_GATEWAY_API_KEY: 'AI_GATEWAY_API_KEY',
  GITHUB_APP_PRIVATE_KEY: 'GITHUB_APP_PRIVATE_KEY',
  HYPERSYNC_API_TOKEN: 'HYPERSYNC_API_TOKEN',
  TELEGRAM_BOT_TOKEN: 'TELEGRAM_BOT_TOKEN',
  TELEGRAM_WEBHOOK_SECRET: 'TELEGRAM_WEBHOOK_SECRET',
  PRIVY_APP_SECRET: 'PRIVY_APP_SECRET',
  PRIVY_SIGNER_KEY: 'PRIVY_SIGNER_KEY',
} as const

export function runtimeSecret(name: keyof typeof prodSecretSources): string | undefined {
  return process.env[name]
}
