/** The connector may authorize only a frozen, owner-approved worker action.
 * This module signs nothing locally. Privy retains W and evaluates its policy.
 */
import { fleetHash, getManagedAgent, type FleetSql } from '@agent-jobs/board'
import * as sdk from '@agent-jobs/sdk'
import { decodeFunctionData, keccak256, parseTransaction, recoverTransactionAddress, type Hex, type TransactionSerialized } from 'viem'
import type { RouteReply } from './oauth.ts'

export const AUTONOMOUS_SIGNING_VERIFIED = false
const fail=(code:string,message:string,status=400):RouteReply=>({status,body:{ok:false,code,message}})
const decode=(value:string)=>Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))
export function canonicalGatewayJson(value:unknown):string {if(value===null||typeof value==='string'||typeof value==='boolean')return JSON.stringify(value);if(typeof value==='number'&&Number.isFinite(value))return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonicalGatewayJson).join(',')}]`;if(typeof value==='object'&&value!==null)return `{${Object.keys(value).toSorted().map(k=>`${JSON.stringify(k)}:${canonicalGatewayJson((value as Record<string,unknown>)[k])}`).join(',')}}`;throw new Error('Request must contain JSON values only')}
export function gatewayDerSignature(signature:string):Uint8Array {const b=decode(signature);if(b.length<8||b[0]!==0x30||b[1]!==b.length-2||b[2]!==2)throw new Error('Invalid P256 signature DER');const rl=b[3]!,r=b.slice(4,4+rl),offset=4+rl;if(rl<1||rl>33||b[offset]!==2)throw new Error('Invalid P256 signature R');const sl=b[offset+1]!,s=b.slice(offset+2);if(sl<1||sl>33||s.length!==sl)throw new Error('Invalid P256 signature S');const raw=new Uint8Array(64);raw.set(r.slice(-32),32-r.slice(-32).length);raw.set(s.slice(-32),64-s.slice(-32).length);return raw}
export async function verifyGatewayAuthorization(publicKey:string,signature:string,input:{method:string;url:string;body:unknown;headers:Record<string,string>}):Promise<boolean>{try{const key=await crypto.subtle.importKey('spki',decode(publicKey),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);return await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,gatewayDerSignature(signature),new TextEncoder().encode(canonicalGatewayJson({version:1,...input})))}catch{return false}}

type GatewayInput={sql:FleetSql;managedId:string;bearer?:string|undefined;body:Record<string,unknown>;now:number;network:sdk.Network;rpcUrl:string;appSecret?:string|undefined;authorityVerified:boolean}
export async function restrictedWalletGateway(input:GatewayInput):Promise<RouteReply>{
 const {sql,managedId,body,now}=input
 // Provider enforcement proof alone is insufficient: owner policy and browser consent must also be proven.
 if(!input.authorityVerified)return fail('unavailable','Automatic wallet authority is disabled until owner consent and scoped provider enforcement are verified',503)
 if(input.network!=='monad-testnet'||!input.rpcUrl||!input.appSecret)return fail('unavailable','Monad testnet signing gateway is unavailable',503)
 const [runtime]=await sql.all<{agent_id:string;public_key:string;generation:number}>('SELECT * FROM agent_runtime WHERE agent_id=? AND token_hash=?',managedId,await fleetHash(input.bearer??''))
 const agent=runtime?await getManagedAgent(sql,managedId):undefined
 if(!runtime||!agent||runtime.generation!==agent.generation)return fail('unauthenticated','Valid runtime pairing required',401)
 if(agent.kind!=='privy'||!agent.privyWalletId||!agent.privyAppId||!agent.agentId||!agent.policyId||agent.status==='stopped')return fail('forbidden','Agent lacks verified identity and owner policy',403)
 const req=body.request as {method?:unknown;url?:unknown;headers?:unknown;body?:unknown}|undefined
 if(!req||req.method!=='POST'||req.url!==`https://api.privy.io/v1/wallets/${agent.privyWalletId}/rpc`||typeof req.headers!=='object'||req.headers===null||typeof req.body!=='object'||req.body===null)return fail('invalid','Exact Privy sign-only request is required')
 const headers=req.headers as Record<string,string>,operationId=String(body.operationId??''),expiry=Number(headers['privy-request-expiry'])
 if(Object.keys(headers).some(k=>!['privy-app-id','privy-request-expiry','privy-idempotency-key'].includes(k))||headers['privy-app-id']!==agent.privyAppId||headers['privy-idempotency-key']!==operationId||!operationId||!Number.isSafeInteger(expiry)||expiry<=now*1000||expiry>now*1000+120000)return fail('forbidden','Request headers, idempotency key or expiry refused',403)
 const providerBody=req.body as Record<string,unknown>,params=providerBody.params as {transaction?:Record<string,unknown>}|undefined,tx=params?.transaction
 if(providerBody.method!=='eth_signTransaction'||!tx||!['2',2].includes(tx.type as string|number)||!(tx.chain_id===10143||tx.chain_id==='10143'||tx.chain_id==='0x279f')||![undefined,'0','0x0',0].includes(tx.value as string|number|undefined)||Object.keys(tx).some(k=>!['type','chain_id','to','data','value','nonce','gas_limit','max_fee_per_gas','max_priority_fee_per_gas','from'].includes(k))||tx.from!==undefined&&String(tx.from).toLowerCase()!==agent.walletAddress.toLowerCase())return fail('forbidden','Only direct zero-value type-2 Monad worker transactions are allowed',403)
 if(!await verifyGatewayAuthorization(runtime.public_key,String(body.authorizationSignature??''),{method:'POST',url:String(req.url),body:providerBody,headers}))return fail('forbidden','P-256 request signature does not match the paired signer',403)
 let operation:'submit'|'dispute';let jobId:bigint
 try{const decoded=decodeFunctionData({abi:sdk.coreAbi,data:String(tx.data) as Hex});if(decoded.functionName!=='submit'||decoded.args[2]!=='0x'||String(tx.to).toLowerCase()!==sdk.deployment(input.network).core.toLowerCase())throw new Error('not submit');operation='submit';jobId=decoded.args[0]}catch{try{const decoded=decodeFunctionData({abi:sdk.hirelingEvaluatorAbi,data:String(tx.data) as Hex});if(decoded.functionName!=='dispute'||String(tx.to).toLowerCase()!==sdk.deployment(input.network).stacks.main!.evaluator.toLowerCase())throw new Error('not dispute');operation='dispute';jobId=decoded.args[0]}catch{return fail('forbidden','Target or function is outside the worker policy',403)}}
 const [approval]=await sql.all<{payload_json:string}>('SELECT payload_json FROM agent_approvals WHERE operation_id=? AND owner=? AND agent_id=? AND status=\'approved\' AND expires_at>?',operationId,agent.owner,agent.id,now)
 const approved=approval?JSON.parse(approval.payload_json) as {tool?:string;from?:string;result?:{transactions?:Array<{to?:string;data?:string;value?:string}>}}:undefined
 if(!approved||approved.from?.toLowerCase()!==agent.walletAddress.toLowerCase()||approved.tool!==(operation==='submit'?'submit_work':'dispute')||approved.result?.transactions?.length!==1||!approved.result.transactions.some(t=>t.to?.toLowerCase()===String(tx.to).toLowerCase()&&t.data===tx.data&&BigInt(t.value??'0')===0n))return fail('forbidden','This exact worker transaction has no live owner approval',403)
 const ctx=sdk.context(input.network,'main',input.rpcUrl),[registered,state]=await Promise.all([sdk.agentWallet(ctx,BigInt(agent.agentId)),sdk.hirelingState(ctx,jobId)])
 if(registered.toLowerCase()!==agent.walletAddress.toLowerCase()||state.job.provider.toLowerCase()!==agent.walletAddress.toLowerCase()||state.paused||operation==='submit'&&(state.status!=='active'||now>state.terms.deliveryDeadline)||operation==='dispute'&&(state.status!=='rejected-pending'||state.disputeEndsAt===null||now>state.disputeEndsAt))return fail('conflict','Current chain state does not permit this worker action',409)
 const requestHash=await fleetHash(canonicalGatewayJson(req)),existing=await sql.all<{request_hash:string;state:string;provider_json:string|null}>('SELECT * FROM agent_gateway_operations WHERE operation_id=?',operationId)
 if(existing[0]){if(existing[0].request_hash!==requestHash)return fail('conflict','This operation already has another exact signing request',409);if(existing[0].provider_json)return {status:200,body:{ok:true,result:{provider:JSON.parse(existing[0].provider_json) as unknown,data:(JSON.parse(existing[0].provider_json) as {data?:unknown}).data,operationId,reconciled:true}}};return fail('conflict','Original signing request is unresolved; reconcile it before retrying',409)}
 const reserved=await sql.all<{operation_id:string}>('INSERT INTO agent_gateway_operations (operation_id,request_hash,state,created_at) VALUES (?,?,\'prepared\',?) ON CONFLICT(operation_id) DO NOTHING RETURNING operation_id',operationId,requestHash,now);if(!reserved[0])return fail('conflict','Operation signing request is already in flight',409)
 const response=await fetch(String(req.url),{method:'POST',redirect:'manual',headers:{authorization:`Basic ${btoa(`${agent.privyAppId}:${input.appSecret}`)}`,...headers,'privy-authorization-signature':String(body.authorizationSignature),'content-type':'application/json'},body:canonicalGatewayJson(providerBody)})
 if(!response.ok)return fail('unavailable',`Privy refused this operation (${response.status}); reconcile the original request`,503)
 const provider=await response.json() as {data?:{signed_transaction?:string;raw_transaction?:string}},raw=(provider.data?.signed_transaction??provider.data?.raw_transaction) as Hex|undefined
 if(!raw)return fail('unavailable','Privy returned no signed raw transaction',503)
 const decoded=parseTransaction(raw as TransactionSerialized),signer=await recoverTransactionAddress({serializedTransaction:raw as TransactionSerialized});if(signer.toLowerCase()!==agent.walletAddress.toLowerCase()||decoded.chainId!==10143||decoded.to?.toLowerCase()!==String(tx.to).toLowerCase()||decoded.data!==tx.data||decoded.value!==undefined&&decoded.value!==0n||String(decoded.nonce)!==String(Number(BigInt(String(tx.nonce)))))return fail('forbidden','Provider signed transaction differs from the frozen request',403)
 await sql.batch([{query:'UPDATE agent_gateway_operations SET state=\'signed\',provider_json=?,raw_transaction=?,transaction_hash=? WHERE operation_id=? AND request_hash=?',params:[JSON.stringify(provider),raw,keccak256(raw),operationId,requestHash]}])
 return {status:200,body:{ok:true,result:{provider,data:provider.data,operationId}}}
}
