// Generated by scripts/gen-abi.ts from contracts/out/FeeSchedule.sol/FeeSchedule.json. Do not edit.
export const feeScheduleAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "initial",
        "type": "tuple",
        "internalType": "struct IFeeSchedule.Schedule",
        "components": [
          {
            "name": "thresholds",
            "type": "uint256[4]",
            "internalType": "uint256[4]"
          },
          {
            "name": "bps",
            "type": "uint16[4]",
            "internalType": "uint16[4]"
          },
          {
            "name": "treasury",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint48",
        "internalType": "uint48"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancel",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "execute",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "feeBps",
    "inputs": [
      {
        "name": "stake",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pending",
    "inputs": [],
    "outputs": [
      {
        "name": "proposed",
        "type": "tuple",
        "internalType": "struct IFeeSchedule.Schedule",
        "components": [
          {
            "name": "thresholds",
            "type": "uint256[4]",
            "internalType": "uint256[4]"
          },
          {
            "name": "bps",
            "type": "uint16[4]",
            "internalType": "uint16[4]"
          },
          {
            "name": "treasury",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "name": "eta",
        "type": "uint48",
        "internalType": "uint48"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "propose",
    "inputs": [
      {
        "name": "s",
        "type": "tuple",
        "internalType": "struct IFeeSchedule.Schedule",
        "components": [
          {
            "name": "thresholds",
            "type": "uint256[4]",
            "internalType": "uint256[4]"
          },
          {
            "name": "bps",
            "type": "uint16[4]",
            "internalType": "uint16[4]"
          },
          {
            "name": "treasury",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "schedule",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IFeeSchedule.Schedule",
        "components": [
          {
            "name": "thresholds",
            "type": "uint256[4]",
            "internalType": "uint256[4]"
          },
          {
            "name": "bps",
            "type": "uint16[4]",
            "internalType": "uint16[4]"
          },
          {
            "name": "treasury",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "treasury",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ScheduleCancelled",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ScheduleExecuted",
    "inputs": [
      {
        "name": "thresholds",
        "type": "uint256[4]",
        "indexed": false,
        "internalType": "uint256[4]"
      },
      {
        "name": "bps",
        "type": "uint16[4]",
        "indexed": false,
        "internalType": "uint16[4]"
      },
      {
        "name": "treasury",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ScheduleProposed",
    "inputs": [
      {
        "name": "thresholds",
        "type": "uint256[4]",
        "indexed": false,
        "internalType": "uint256[4]"
      },
      {
        "name": "bps",
        "type": "uint16[4]",
        "indexed": false,
        "internalType": "uint16[4]"
      },
      {
        "name": "treasury",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "eta",
        "type": "uint48",
        "indexed": false,
        "internalType": "uint48"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "FeeTooHigh",
    "inputs": [
      {
        "name": "bps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "max",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "FeesIncreasing",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FirstThresholdNotZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoPendingSchedule",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ScheduleTimelocked",
    "inputs": [
      {
        "name": "eta",
        "type": "uint48",
        "internalType": "uint48"
      }
    ]
  },
  {
    "type": "error",
    "name": "ThresholdsNotAscending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroTreasury",
    "inputs": []
  }
] as const
