// Generated by scripts/gen-abi.ts from contracts/out/JobPoolFactory.sol/JobPoolFactory.json. Do not edit.
export const jobPoolFactoryAbi = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "allPools",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "create",
    "inputs": [
      {
        "name": "userSalt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct JobPool.Params",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "contract IERC20"
          },
          {
            "name": "goal",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pledgeDeadline",
            "type": "uint48",
            "internalType": "uint48"
          },
          {
            "name": "curator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "holding",
            "type": "address",
            "internalType": "contract JobHolding"
          },
          {
            "name": "publish",
            "type": "tuple",
            "internalType": "struct JobHolding.PublishParams",
            "components": [
              {
                "name": "approver",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "manifestHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "policyHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "token",
                "type": "address",
                "internalType": "contract IERC20"
              },
              {
                "name": "reward",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "creatorBond",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "workerBond",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "deliveryDeadline",
                "type": "uint48",
                "internalType": "uint48"
              },
              {
                "name": "expiredAt",
                "type": "uint48",
                "internalType": "uint48"
              },
              {
                "name": "mode",
                "type": "uint8",
                "internalType": "enum JobHolding.Mode"
              },
              {
                "name": "selectionDeadline",
                "type": "uint48",
                "internalType": "uint48"
              }
            ]
          },
          {
            "name": "governance",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "holdProvider",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "pool",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "implementation",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract JobPool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "poolCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predict",
    "inputs": [
      {
        "name": "creator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "userSalt",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "PoolCreated",
    "inputs": [
      {
        "name": "pool",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "creator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "curator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "token",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "goal",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "pledgeDeadline",
        "type": "uint48",
        "indexed": false,
        "internalType": "uint48"
      },
      {
        "name": "holding",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "policyHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "FailedDeployment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientBalance",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const
