#!/usr/bin/env node
/**
 * The skill files in skill/ are the single source for what hosted MCP tells agents: `initialize` instructions come
 * from skill/connector/INSTRUCTIONS.md and get_instructions / sidequest://skills/<role> serve the role SKILL.md body.
 * This writes apps/api/src/generated/skills.ts (the Worker cannot read the repo at runtime). `--check` fails when the
 * checked-in file is stale.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'
import { parse } from 'yaml'

const root = fileURLToPath(new URL('..', import.meta.url))
export const ROLES = ['connector', 'worker', 'publisher']
export const OUTPUT = 'apps/api/src/generated/skills.ts'

/** A SKILL.md without its YAML front matter. */
export const skillBody = (text) => text.replace(/^---\n[\s\S]*?\n---\n+/, '')

export function skillManifest(role, raw) {
  const yaml = /^---\n([\s\S]*?)\n---\n/.exec(raw)?.[1]
  if (yaml === undefined) return undefined
  const frontmatter = parse(yaml)
  if (typeof frontmatter?.name !== 'string' || typeof frontmatter?.description !== 'string') return undefined
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(frontmatter.name) || frontmatter.description.trim() === '')
    throw new Error(`Invalid skill frontmatter: ${role}`)
  const size = Buffer.byteLength(raw, 'utf8')
  if (size > 262_144) throw new Error(`SKILL.md exceeds 256 KiB: ${role}`)
  const uri = `skill://sidequest/${frontmatter.name}/SKILL.md`
  return {
    uri,
    frontmatter,
    resources: [{ uri, digest: `sha256:${createHash('sha256').update(raw, 'utf8').digest('hex')}`, size }],
    raw,
  }
}

export function render(read = (path) => readFileSync(`${root}${path}`, 'utf8')) {
  const skills = Object.fromEntries(ROLES.map((role) => [role, skillBody(read(`skill/${role}/SKILL.md`)).trimEnd()]))
  // Arbitrator guidance targets a separate key-holding surface; do not advertise it to hosted-agent clients.
  const manifests = ROLES.map((role) => skillManifest(role, read(`skill/${role}/SKILL.md`))).filter(Boolean)
  if (manifests.length > 5) throw new Error('At most five static skills may be advertised')
  return [
    '// Generated by scripts/gen-skills.mjs from skill/. Do not edit; run `node scripts/gen-skills.mjs`.',
    `export const CONNECTOR_INSTRUCTIONS = ${JSON.stringify(read('skill/connector/INSTRUCTIONS.md').trimEnd())}`,
    `export const SKILLS = ${JSON.stringify(skills, null, 2)} as const`,
    `export const SKILL_MANIFESTS = ${JSON.stringify(manifests, null, 2)} as const`,
    `export async function renderedSkillManifests(origin: string) {
  const site = new URL(origin).origin
  return Promise.all(SKILL_MANIFESTS.map(async skill => {
    const raw = skill.raw.replaceAll('{{SIDEQUEST_ORIGIN}}', site)
    const bytes = new TextEncoder().encode(raw)
    const hash = await crypto.subtle.digest('SHA-256', bytes)
    const digest = 'sha256:' + Array.from(new Uint8Array(hash), byte => byte.toString(16).padStart(2, '0')).join('')
    return { ...skill, raw, resources: skill.resources.map(resource => ({ ...resource, digest, size: bytes.byteLength })) }
  }))
}`,
    '',
  ].join('\n')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = render()
  if (process.argv.includes('--check')) {
    if (readFileSync(`${root}${OUTPUT}`, 'utf8') !== next) {
      console.error(`${OUTPUT} is stale; run node scripts/gen-skills.mjs`)
      process.exit(1)
    }
  } else writeFileSync(`${root}${OUTPUT}`, next)
}
