/**
 * Copies the ABIs the SDK needs from Foundry's build output into typed `as const` modules, so viem infers
 * every call and event. Run after `forge build` whenever a contract's interface changes:
 *
 *   bun scripts/gen-abi.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..')
const out = join(root, 'contracts/out')
const target = join(root, 'packages/sdk/src/abi')

type AbiItem = { type: string; name?: string; inputs?: Array<{ type: string }> }
type Source = [file: string, name: string]

/**
 * `extra` sources are merged into the ABI. The Hireling v1 entries (ADR-0011) are provisional: generated from the
 * interfaces in `contracts/src/hireling/interfaces/`, with the `Ownable2Step` surface the implementations inherit from
 * OpenZeppelin merged in. They switch to the implementations under the same export names once those exist.
 */
const contracts: Array<[file: string, name: string, module: string, exportName: string, extra?: Source[]]> = [
  ['JobHolding.sol', 'JobHolding', 'holding', 'jobHoldingAbi'],
  ['JobsEvaluator.sol', 'JobsEvaluator', 'evaluator', 'jobsEvaluatorAbi'],
  ['ERC8183WithAuthorization.sol', 'ERC8183WithAuthorization', 'core', 'coreAbi'],
  ['FactoryToken.sol', 'FactoryToken', 'factory', 'factoryTokenAbi'],
  ['MockPaymentToken.sol', 'MockPaymentToken', 'faucetToken', 'faucetTokenAbi'],
  ['IERC8004.sol', 'IERC8004Identity', 'identity', 'identityAbi'],
  ['IERC8004.sol', 'IERC8004Reputation', 'reputation', 'reputationAbi'],
  ['JobPool.sol', 'JobPool', 'pool', 'jobPoolAbi'],
  ['JobPoolFactory.sol', 'JobPoolFactory', 'poolFactory', 'jobPoolFactoryAbi'],
  ['HirelingHolding.sol', 'HirelingHolding', 'hirelingHolding', 'hirelingHoldingAbi'],
  ['HirelingEvaluator.sol', 'HirelingEvaluator', 'hirelingEvaluator', 'hirelingEvaluatorAbi'],
  ['StakeVault.sol', 'StakeVault', 'stakeVault', 'stakeVaultAbi'],
  ['FeeSchedule.sol', 'FeeSchedule', 'feeSchedule', 'feeScheduleAbi'],
  ['Factory.sol', 'Factory', 'factoryV2', 'factoryV2Abi'],
  ['IMiningReserve.sol', 'IMiningReserve', 'miningReserve', 'miningReserveAbi', [ownable()]],
  ['IEpochDistributor.sol', 'IEpochDistributor', 'epochDistributor', 'epochDistributorAbi', [ownable()]],
]

function ownable(): Source {
  return ['IOwnable2Step.sol', 'IOwnable2Step']
}

function readAbi([file, name]: Source): AbiItem[] {
  return (JSON.parse(readFileSync(join(out, file, `${name}.json`), 'utf8')) as { abi: AbiItem[] }).abi
}

/** Same type, name and input types = the same item; the first source wins. */
function key(item: AbiItem): string {
  return `${item.type}:${item.name ?? ''}(${(item.inputs ?? []).map((input) => input.type).join(',')})`
}

const index: string[] = []
for (const [file, name, module, exportName, extra = []] of contracts) {
  const abi = readAbi([file, name])
  const seen = new Set(abi.map(key))
  for (const source of extra) {
    for (const item of readAbi(source)) {
      if (seen.has(key(item))) continue
      seen.add(key(item))
      abi.push(item)
    }
  }
  const from = [[file, name] as Source, ...extra].map(([f, n]) => `contracts/out/${f}/${n}.json`).join(' + ')
  writeFileSync(
    join(target, `${module}.ts`),
    `// Generated by scripts/gen-abi.ts from ${from}. Do not edit.\n` +
      `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const\n`,
  )
  index.push(`export { ${exportName} } from './${module}.ts'`)
}
writeFileSync(join(target, 'index.ts'), `${index.join('\n')}\n`)
console.log(`wrote ${contracts.length} ABIs to packages/sdk/src/abi`)
