/**
 * Copies the ABIs the SDK needs from Foundry's build output into typed `as const` modules, so viem infers
 * every call and event. Run after `forge build` whenever a contract's interface changes:
 *
 *   bun scripts/gen-abi.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..')
const out = join(root, 'contracts/out')
const target = join(root, 'packages/sdk/src/abi')

const contracts: Array<[file: string, name: string, module: string, exportName: string]> = [
  ['JobHolding.sol', 'JobHolding', 'holding', 'jobHoldingAbi'],
  ['JobsEvaluator.sol', 'JobsEvaluator', 'evaluator', 'jobsEvaluatorAbi'],
  ['ERC8183WithAuthorization.sol', 'ERC8183WithAuthorization', 'core', 'coreAbi'],
  ['FactoryToken.sol', 'FactoryToken', 'factory', 'factoryTokenAbi'],
  ['MockPaymentToken.sol', 'MockPaymentToken', 'faucetToken', 'faucetTokenAbi'],
  ['IERC8004.sol', 'IERC8004Identity', 'identity', 'identityAbi'],
  ['IERC8004.sol', 'IERC8004Reputation', 'reputation', 'reputationAbi'],
]

const index: string[] = []
for (const [file, name, module, exportName] of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, file, `${name}.json`), 'utf8')) as { abi: unknown }
  writeFileSync(
    join(target, `${module}.ts`),
    `// Generated by scripts/gen-abi.ts from contracts/out/${file}/${name}.json. Do not edit.\n` +
      `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const\n`,
  )
  index.push(`export { ${exportName} } from './${module}.ts'`)
}
writeFileSync(join(target, 'index.ts'), `${index.join('\n')}\n`)
console.log(`wrote ${contracts.length} ABIs to packages/sdk/src/abi`)
