#!/usr/bin/env node
/**
 * The docs pages are the single source for hosted MCP documentation. This writes
 * apps/api/src/generated/docs.ts; `--check` fails when that file is stale.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const docsRoot = resolve(root, 'apps/docs')
const output = join(root, 'apps/api/src/generated/docs.ts')
const placeholder = 'https://sidequest.origin.invalid'
// Resolve the content pipeline's dependencies from its owning pnpm workspace.
const requireDocs = createRequire(join(docsRoot, 'package.json'))
const { default: react } = await import(pathToFileURL(requireDocs.resolve('@vitejs/plugin-react')).href)
const { createServer } = await import(pathToFileURL(requireDocs.resolve('vite')).href)
const { fumadocsMdx } = await import(pathToFileURL(requireDocs.resolve('fumadocs-mdx/vite')).href)

function option(name) {
  const index = process.argv.indexOf(name)
  return index === -1 ? undefined : process.argv[index + 1]
}

async function loadDocs() {
  process.env.SIDEQUEST_DOCS_ORIGIN = placeholder
  process.env.SIDEQUEST_DOCS_EXPORT = '1'
  const server = await createServer({
    root: docsRoot,
    configFile: false,
    envDir: false,
    plugins: [...fumadocsMdx(), react()],
    define: { __DOCS_ORIGIN__: JSON.stringify(placeholder) },
    resolve: { tsconfigPaths: true },
    server: { middlewareMode: true, hmr: false, watch: null },
    appType: 'custom',
    optimizeDeps: { noDiscovery: true, include: [] },
  })
  try {
    const module = await server.ssrLoadModule('/src/lib/export.ts')
    return await module.exportDocs()
  } finally {
    await server.close()
  }
}

function render(docs) {
  return [
    '// Generated by scripts/gen-docs.mjs from apps/docs/content. Do not edit; run `node scripts/gen-docs.mjs`.',
    `export const DOCS_ORIGIN_PLACEHOLDER = '${placeholder}'`,
    `export const DOCS = ${JSON.stringify(docs, null, 2)} as const`,
    '',
  ].join('\n')
}

function diffContext(text, position) {
  return JSON.stringify(text.slice(Math.max(0, position - 32), position + 80))
}

function mismatch(expected, actual) {
  let at = 0
  while (at < expected.length && at < actual.length && expected[at] === actual[at]) at += 1
  return `at ${at}: expected ${diffContext(expected, at)}, got ${diffContext(actual, at)}`
}

async function parity(docs, siteDir, origin) {
  if (siteDir === undefined) throw new Error('--parity requires a site output directory')
  const failures = []
  for (const page of docs) {
    const file = join(resolve(siteDir), 'docs', `${page.slug}.md`)
    let actual
    try { actual = readFileSync(file, 'utf8') } catch { failures.push(`${file}: missing`); continue }
    const expected = page.markdown.replaceAll(placeholder, origin)
    if (actual !== expected) failures.push(`${file}: ${mismatch(expected, actual)}`)
  }
  if (failures.length > 0) throw new Error(`Docs Markdown parity failed:\n${failures.join('\n')}`)
}

const docs = await loadDocs()
const next = render(docs)
if ((process.argv.includes('--check') || process.argv.includes('--parity')) && readFileSync(output, 'utf8') !== next) {
  console.error(`${output} is stale; run node scripts/gen-docs.mjs`)
  process.exitCode = 1
} else if (process.argv.includes('--parity')) {
  await parity(docs, option('--parity'), new URL(option('--origin') ?? 'http://localhost:5173').origin)
  console.log(`Verified Markdown parity for ${docs.length} MCP docs pages`)
} else if (!process.argv.includes('--check')) {
  writeFileSync(output, next)
}
