/**
 * Copies the ABIs the SDK needs from Foundry's build output into typed `as const` modules, so viem infers
 * every call and event. Run after `forge build` whenever a contract's interface changes:
 *
 *   bun scripts/gen-abi.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..')
const out = join(root, 'contracts/out')
const target = join(root, 'packages/sdk/src/abi')

/** The Sidequest v1 entries (ADR-0011) come from the implementations in `contracts/src/sidequest/`. */
const contracts: Array<[file: string, name: string, module: string, exportName: string]> = [
  ['JobHolding.sol', 'JobHolding', 'holding', 'jobHoldingAbi'],
  ['JobsEvaluator.sol', 'JobsEvaluator', 'evaluator', 'jobsEvaluatorAbi'],
  ['ERC8183WithAuthorization.sol', 'ERC8183WithAuthorization', 'core', 'coreAbi'],
  ['FactoryToken.sol', 'FactoryToken', 'factory', 'factoryTokenAbi'],
  ['MockPaymentToken.sol', 'MockPaymentToken', 'faucetToken', 'faucetTokenAbi'],
  ['IERC8004.sol', 'IERC8004Identity', 'identity', 'identityAbi'],
  ['IERC8004.sol', 'IERC8004Reputation', 'reputation', 'reputationAbi'],
  ['JobPool.sol', 'JobPool', 'pool', 'jobPoolAbi'],
  ['JobPoolFactory.sol', 'JobPoolFactory', 'poolFactory', 'jobPoolFactoryAbi'],
  ['SidequestHolding.sol', 'SidequestHolding', 'sidequestHolding', 'sidequestHoldingAbi'],
  ['SidequestEvaluator.sol', 'SidequestEvaluator', 'sidequestEvaluator', 'sidequestEvaluatorAbi'],
  ['StakeVault.sol', 'StakeVault', 'stakeVault', 'stakeVaultAbi'],
  ['FeeSchedule.sol', 'FeeSchedule', 'feeSchedule', 'feeScheduleAbi'],
  ['Factory.sol', 'Factory', 'factoryV2', 'factoryV2Abi'],
  ['MiningReserve.sol', 'MiningReserve', 'miningReserve', 'miningReserveAbi'],
  ['EpochDistributor.sol', 'EpochDistributor', 'epochDistributor', 'epochDistributorAbi'],
  ['TestnetFaucet.sol', 'TestnetFaucet', 'testnetFaucet', 'testnetFaucetAbi'],
  ['V4SwapHelper.sol', 'V4SwapHelper', 'v4SwapHelper', 'v4SwapHelperAbi'],
]

const index: string[] = []
for (const [file, name, module, exportName] of contracts) {
  // Registry wallet consent is an external interface, already verified in the retained ERC-8004 ABI.
  // Keep the SDK subset generated from that source; no deployed Sidequest interface changes.
  const registryMethods = new Set(['register', 'ownerOf', 'getAgentWallet', 'isAuthorizedOrOwner', 'setMetadata', 'getMetadata', 'setAgentWallet', 'unsetAgentWallet', 'Registered'])
  const artifact = module === 'identity'
    ? { abi: (JSON.parse(readFileSync(join(root, 'contracts/abi/erc8004/IdentityRegistry.json'), 'utf8')) as Array<{ name?: string }>).filter(item => registryMethods.has(item.name ?? '')) }
    : JSON.parse(readFileSync(join(out, file, `${name}.json`), 'utf8')) as { abi: unknown }
  const source = module === 'identity' ? 'contracts/abi/erc8004/IdentityRegistry.json' : `contracts/out/${file}/${name}.json`
  writeFileSync(
    join(target, `${module}.ts`),
    `// Generated by scripts/gen-abi.ts from ${source}. Do not edit.\n` +
      `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const\n`,
  )
  index.push(`export { ${exportName} } from './${module}.ts'`)
}
writeFileSync(join(target, 'index.ts'), `${index.join('\n')}\n`)
console.log(`wrote ${contracts.length} ABIs to packages/sdk/src/abi`)
