import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
const source = new URL('../apps/api/src/hiring/', import.meta.url)
const script = readFileSync(new URL('panel.js', source), 'utf8')
const style = readFileSync(new URL('panel.css', source), 'utf8')
const digest = createHash('sha256').update(script).digest('base64')
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'sha256-${digest}'; style-src 'unsafe-inline'; connect-src 'none'; frame-src 'none'; base-uri 'none'; form-action 'none'"><title>Sidequest · Hiring desk</title><style>${style}</style></head><body><main><header><span class="brand">Sidequest / Hiring desk</span><nav class="toolbar" aria-label="Hiring views"><button id="dashboard" disabled>Dashboard</button><button id="refresh" disabled>Refresh facts</button><button id="context" hidden>Add to conversation</button><button id="fullscreen" hidden>Expand</button></nav></header><div id="status" role="status" aria-live="polite">Connecting to the host…</div><button id="retry" hidden>Reconcile / retry identical action</button><section id="confirmation" hidden aria-label="Confirm exact action"></section><section id="content" aria-label="Hiring activity"></section></main><script>${script}</script></body></html>`
if (Buffer.byteLength(html) >= 300 * 1024) throw new Error('Hiring App exceeds 300 KiB')
const generated = `// Generated by scripts/gen-hiring.mjs. Breaking changes require ui://sidequest/hiring/v2.html.\nexport const hiringHtml = ${JSON.stringify(html)}\n`
const output = new URL('../apps/api/src/generated/hiring.ts', import.meta.url)
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== generated)
    throw new Error('Run node scripts/gen-hiring.mjs; hiring App is stale')
} else writeFileSync(output, generated)
