#!/usr/bin/env node
/**
 * The skill files in skill/ are the single source for what hosted MCP tells agents: `initialize` instructions come
 * from skill/connector/INSTRUCTIONS.md and get_instructions / hireling://skills/<role> serve the role SKILL.md body.
 * This writes apps/api/src/generated/skills.ts (the Worker cannot read the repo at runtime). `--check` fails when the
 * checked-in file is stale.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
export const ROLES = ['connector', 'worker', 'publisher']
export const OUTPUT = 'apps/api/src/generated/skills.ts'

/** A SKILL.md without its YAML front matter. */
export const skillBody = text => text.replace(/^---\n[\s\S]*?\n---\n+/, '')

export function render(read = path => readFileSync(`${root}${path}`, 'utf8')) {
  const skills = Object.fromEntries(ROLES.map(role => [role, skillBody(read(`skill/${role}/SKILL.md`)).trimEnd()]))
  return [
    '// Generated by scripts/gen-skills.mjs from skill/. Do not edit; run `node scripts/gen-skills.mjs`.',
    `export const CONNECTOR_INSTRUCTIONS = ${JSON.stringify(read('skill/connector/INSTRUCTIONS.md').trimEnd())}`,
    `export const SKILLS = ${JSON.stringify(skills, null, 2)} as const`,
    '',
  ].join('\n')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = render()
  if (process.argv.includes('--check')) {
    if (readFileSync(`${root}${OUTPUT}`, 'utf8') !== next) { console.error(`${OUTPUT} is stale; run node scripts/gen-skills.mjs`); process.exit(1) }
  } else writeFileSync(`${root}${OUTPUT}`, next)
}
